---
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      # Instructs ZooKeeper where to listen for connections by clients such as Apache Kafka®
      ZOOKEEPER_CLIENT_PORT: 2181
      # The length of a single tick, which is the basic time unit used by ZooKeeper, as measured in milliseconds.
      # It is used to regulate heartbeats, and timeouts. For example, the minimum session timeout will be two ticks.
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.2.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      # Instructs Kafka how to get in touch with ZooKeeper
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # This is required when you are running with a single-node cluster.
      # If you have three or more nodes, you can use the default.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # LISTENERS are what interfaces Kafka binds to. ADVERTISED_LISTENERS are how clients can connect.
      # KAFKA_ADVERTISED_LISTENERS is a comma-separated list of listeners with their the host/ip and port.
      # https://rmoff.net/2018/08/02/kafka-listeners-explained/
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP defines key/value pairs for the security protocol to use, per listener name.
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT

  kafka-helper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-helper
    depends_on:
      - broker
    environment:
      ZOOKEEPER: zookeeper:2181
      BOOTSTRAP_BROKERS: broker:29092
      DEFAULT_REPLICATION_FACTOR: 1
      DEFAULT_PARTITIONS_NUMBER: 1
